formatter: markdown

header-from: main.tf

output:
  file: README.md
  mode: replace
  template: |-
    {{ .Content }}

content: |-
  {{ .Header }}

  ## Example

  ```hcl
  {{ include "examples/vpc/main.tf" }}
  ```

  {{ .Inputs }}

  {{ .Outputs }} 
