{{- if .Values.datagrok.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    name: {{ template "datagrok.fullname" $ }}-config-cm
  labels:
    {{- include "datagrok.labels" . | nindent 4 }}
  name: {{ template "datagrok.fullname" $ }}-config-cm
data:
  config.json: |-
    {
      "deployDemo": false,
      "dbServer": "database",
      "db": "datagrok",
      "dbAdminLogin": "{{ .Values.datagrok.db_admin_user }}",
      "dbAdminPassword": "{{ .Values.datagrok.db_admin_password }}",
      "dbLogin": "dg",
      "dbPassword": "dg",
      "adminPassword": "admin",
      "adminDevKey": "admin",
      "isolatesCount": 2,
      "connectorsSettings": {
        "dataframeParsingMode":"New Process",
        "externalDataFrameCompress":true,
        "grokConnectHost":"grok_connect",
        "grokConnectPort":1234,
        "localFileSystemAccess":false,
        "sambaSpaceEscape":"none",
        "sambaVersion":"3.0"
      },
      "dockerSettings": {
          "grokSpawnerApiKey": "test-x-api-key",
          "grokSpawnerHost": "grok_spawner",
          "grokSpawnerPort": 8000,
          "imageBuildTimeoutMinutes": 30,
          "proxyRequestTimeout": 60000
      },
      "queueSettings": {
        "amqpHost": "rabbitmq",
        "amqpPassword": "guest",
        "amqpPort": 5672,
        "amqpUser": "guest",
        "pipeHost": "grok_pipe",
        "pipeKey": "test-key"
      }
    }
{{- end }}