{{- if .Values.grok_pipe.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "datagrok.fullname" . }}-grok-pipe
  labels:
  {{- include "datagrok-grok-pipe.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "datagrok-grok-pipe.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 120
  template:
    metadata:
      annotations:
      {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datagrok-grok-pipe.labels" . | nindent 8 }}
    spec:
      containers:
        - name: pipe
          image: "{{ .Values.grok_pipe.image.docker_image }}:{{ .Values.grok_pipe.image.tag }}"
          imagePullPolicy: {{ .Values.grok_pipe.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ template "datagrok.fullname" $ }}-grok-pipe-cm
              optional: false
          ports:
            - name: service
              containerPort: {{ .Values.grok_pipe.ports.service.port }}
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: {{ .Values.security.userNameId }}
            capabilities:
              drop:
                - all
              add: ["MKNOD"]
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- toYaml (omit .Values.startupProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      securityContext:
        fsGroup: {{ .Values.security.userGroupId }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    name: {{ template "datagrok.fullname" $ }}-grok-pipe-cm
  labels:
    {{- include "datagrok-grok-pipe.labels" . | nindent 4 }}
  name: {{ template "datagrok.fullname" $ }}-grok-pipe-cm
data:
  {{- range $key, $val := .Values.grok_pipe.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "datagrok-grok-pipe.labels" . | nindent 4 }}
  name: {{ template "datagrok.fullname" $ }}-grok-pipe
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.grok_pipe.ports.service.port }}
    targetPort: service
    name: service
  selector:
{{- include "datagrok-grok-pipe.selectorLabels" . | nindent 4 }}

{{- end }}

