{{- if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "datagrok.fullname" $ }}
  labels:
    {{- include "datagrok.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  {{- if .Values.custom_cert }}
  tls:
    - hosts:
        - {{ .Values.ingress.fqdn }}
        secretName: cert-{{ .Values.ingress.subdomain }}-{{ template "datagrok.certSecretName" $ }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.fqdn }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "datagrok.fullname" $ }}
                port:
                  name: http
{{- end }}
