# File: .github/workflows/gcp-deploy.yaml
# rev.0.0.4
#
# Last modified: 2025/07/27 21:04:50

# Secrets:
#   GCP_SERVICE_ACCOUNT_KEY
#   GCP_PROJECT_ID
#   GCP_PROJECT_STATEFILE_BUCKET
#   GCP_PROJECT_STATEFILE_PREFIX
# Variables:
#   APP_NAME
#   GOOGLE_CORE_REGION
#   GOOGLE_CLUSTER_ZONE

name: "Deploy GCP"

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - stage

permissions:
  contents: read

env:
  TF_WORKSPACE: ${{ github.ref_name }}
  TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}

defaults:
  run:
    shell: bash

jobs:
  infra:
    name: "${{ github.ref_name }}"
    uses: ./.github/workflows/gcp-terraform.yaml
    with:
      working_directory: "./gcp"
      stage: ${{ github.ref_name }}
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"

  helm:
    name: "Apps"
    needs:
      - infra
    secrets: inherit
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/gcp-helm.yaml
    with:
      working_directory: "./helm"
      app_name: ${{ vars.APP_NAME || 'datagrok' }}
      stage: ${{ github.ref_name }}
      # cluster_name: ${{ needs.infra.outputs.cluster_name }}
      # cluster_location: ${{ needs.infra.outputs.cluster_location}}
      # workaround till develop
      cluster_name: "gke-develop-1"
      cluster_location: "europe-west3-a"
      subdomain: ${{ github.ref_name }}
      # service_account_credentials_json: ${{ needs.infra.service_account_credentials_json }}

  post:
    name: "Results"
    needs:
      - infra
      - helm
    if: true
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    defaults:
      run:
        shell: bash
    steps:
      - run: |
          echo $GITHUB_OUTPUT
          echo "Pipeline finished!"
